version: '3'
services:
  trashtrack_sql:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Word5678?
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - trashtracknet2023
      
networks:
  trashtracknet2023:
    driver: bridge
